identity.cookie.secure=false
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:false}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS:false}
spring.mail.properties.mail.smtp.starttls.required=${MAIL_STARTTLS:false}

media.worker.enabled=${MEDIA_WORKER_ENABLED:true}
media.storage.mode=local
media.storage.region=us-east-1
media.storage.endpoint=${MEDIA_ENDPOINT:http://localhost:9090}
media.storage.public-endpoint=${MEDIA_PUBLIC_ENDPOINT:http://localhost:9090}
media.storage.staging-bucket=geer-staging-local
media.storage.frozen-bucket=geer-frozen-local
